### ISSUE TITLE
asdf only shows version 0.1.0 available

### ISSUE THREAD

**Issue by philpennock** [Luizm/asdf-shfmt#2]
When `asdf list-all shfmt` is run, it only reports version 0.1.0.

Invoking `~/.asdf/plugins/shfmt/bin/list-all` shows a rather more complete list.

The problem is that shfmt's `list-all` is reporting one version per line, while `asdf` wants all versions on a single line with a single space as the separator between each version.

<https://asdf-vm.com/#/plugins-create?id=binlist-all>

> Must print a string with a space-separated list of versions.

Note that the text a little after that, `since the list-all command prints each version on it’s own line`, appears to be unfortunate wording talking about how `asdf list-all FOO` behaves, not about the API which FOO is expected to fulfill.

**Comment by luizm** [comment]
Hi @philpennock Thanks for the report, Could you try again?

**Comment by philpennock** [comment]
Works for me now. Thanks.
